#!/system/bin/sh

# geomagnetic
chown system.input /sys/class/input/input8/data
chown system.input /sys/class/input/input8/delay
chown system.input /sys/class/input/input8/enable
chown system.input /sys/class/input/input8/filter_enable
chown system.input /sys/class/input/input8/filter_len
chown system.input /sys/class/input/input8/filter_noise
chown system.input /sys/class/input/input8/filter_threshold
chown system.input /sys/class/input/input8/position
chown system.input /sys/class/input/input8/wake
chmod 666 /sys/class/input/input8/data
chmod 666 /sys/class/input/input8/delay
chmod 666 /sys/class/input/input8/enable
chmod 666 /sys/class/input/input8/filter_enable
chmod 666 /sys/class/input/input8/filter_len
chmod 666 /sys/class/input/input8/filter_noise
chmod 666 /sys/class/input/input8/filter_threshold
chmod 666 /sys/class/input/input8/position
chmod 666 /sys/class/input/input8/wake

# geomagnetic_raw
chown compass.input /sys/class/input/input9/dynamic_matrix
chown compass.input /sys/class/input/input9/offsets
chown system.input /sys/class/input/input9/distortion
chown system.input /sys/class/input/input9/ellipsoid_mode
chown system.input /sys/class/input/input9/shape
chown system.input /sys/class/input/input9/static_matrix
chmod 666 /sys/class/input/input9/dynamic_matrix
chmod 666 /sys/class/input/input9/offsets
chmod 666 /sys/class/input/input9/distortion
chmod 666 /sys/class/input/input9/ellipsoid_mode
chmod 666 /sys/class/input/input9/shape
chmod 666 /sys/class/input/input9/static_matrix

# compass
echo 0 > /sys/class/input/input9/ellipsoid_mode 0
echo "10319 -477 45 -147 9510 171 -170 52 10187" > /sys/class/input/input9/static_matrix

start geomagneticd


